$extends: base
subsystems:
    drivetrain:
        implemented: true
        talons:
            leftMain: 15
            leftFollower: -1
            rightMain: 13
            rightFollower: -1
            flAzimuth: 1
            blAzimuth: -1
            frAzimuth: -1
            brAzimuth: -1
        swerveModules:
            frontLeft:
                drive: leftMain
                azimuth: flAzimuth
                encoderOffset: 2837
            frontRight:
                drive: rightMain
                azimuth: frAzimuth
                encoderOffset: 3335
            backLeft:
                drive: leftFollower
                azimuth: blAzimuth
                encoderOffset: 5
            backRight:
                drive: rightFollower
                azimuth: brAzimuth
                encoderOffset: 2582
        drivePid:
            kP: 3.0 # 0.18 # TODO: tune PID, these are temporary PID values from Zeta
            kI: 0.03 # 0.018
            kD: 36 # 3.6
            kF: 0.96
        azimuthPid:
            kP: 1.0
            kI: 0.001
            kD: 10
            kF: 0
        invertMotor:
            - rightMain
        constants:
            pigeonId: 9
            encPPR: 999
            azimuthEncPPR: 4096
            azimuthAllowableErrorTicks: 10
pcm: 8
constants:
    maxVel: 120 # inches/s
    maxAccel: 60 # inches/s^2
    trackWidth: 23 # inches
    wheelDiameter: 6.122 #inches
    logTeleop: 1
    logAuto: 1
    badLogEnabled: 1
