$extends: zodiac_base
subsystems:
    drivetrain:
        implemented: true
        talons:
            leftMain: 15
            leftFollower: 14
            leftFollowerTwo: -1
            rightMain: 13
            rightFollower: 12
            rightFollowerTwo: -1
        constants:
            pigeonId: -1
            pigeonOnTalon: -1
            kP: 0 # 0.18 # TODO: tune PID, these are temporary PID values from Zeta
            kI: 0 # 0.018
            kD: 0 # 3.6
            kF: 0
            iZone: 0
            encPPR: 22220.8
            currentFloorCheck: .12
            currentEpsilonCheck: .2
            rpmFloorCheck: 2000
            rpmEpsilonCheck: 60
            openLoopRampRate: 0.8
    climber:
        implemented: false
        invertMotor:
            - elevator
    hopper:
        implemented: false
        invertMotor:
            - elevator
    shooter:
        implemented: false
        falcons:
            shooterMain: 3
            shooterFollower: 2
    turret:
        implemented: false
        constants:
            minPos: -3802
            maxPos: -757
    ledmanager:
        implemented: false
        canifier: 18
    camera:
        implemented: false
        canifier: 19
constants:
    wheelDiameter: 6.32 #inches
    logTeleop: 1
    logAuto: 1
    badLogEnabled: 1
