$extends: base
subsystems:
    drivetrain:
        implemented: true
        talons:
            leftMain: 15
            leftFollower: 14
            leftFollowerTwo: -1
            rightMain: 13
            rightFollower: 12
            rightFollowerTwo: -1
        invertMotor:
            - rightMain
        constants:
            pigeonId: 9
            kP: 0.623 # 0.18 # TODO: tune PID, these are temporary PID values from Zeta
            kI: 0 # 0.018
            kD: 0 # 3.6
            kF: 0.87
            encPPR: 999
pcm: 8
constants:
    trackWidth: 23 # inches
    wheelDiameter: 6.32 #inches
    logTeleop: 1
    logAuto: 1
    badLogEnabled: 1
