subsystems:
    drivetrain:
        implemented: true
        talons:
            leftMain: 15
            leftFollower: -1
            rightMain: 13
            rightFollower: -1
        pidConfig:
            slot0:
                kP: 0.1 # 0.18 # TODO: tune PID, these are temporary PID values from Zeta
                kI: 0.0001 # 0.018
                kD: 4.0 # 3.6
                kF: 0.0475813
            slot1:
                kP: 3.0
                kI: 0.018
                kD: 4.2
                kF: 0.042
        invertMotor:
            - rightMain
        constants:
            pigeonId: 9
            pigeonOnTalon: -1
            currentFloorCheck: .12
            currentEpsilonCheck: .2
            kP: 3.0 # 0.18 # TODO: tune PID, these are temporary PID values from Zeta
            kI: 0.03 # 0.018
            kD: 36 # 3.6
            kF: 0.96
            rpmFloorCheck: 2000
            rpmEpsilonCheck: 60
            openLoopRampRate: 0.8
            isSwerve: 0
            encPPR: 999
            azimuthEncPPR: 4096
            azimuthAllowableErrorTicks: 10
pcm: 8
constants:
    maxTicks: 14000 # ticks per 100ms TODO test actual maxTicks value
    sensorPhase: 0
    kLooperDt: .010
    kP: 3.0 # 0.18 # TODO: tune PID, these are temporary PID values from Zeta
    kI: 0.03 # 0.018
    kD: 36 # 3.6
    kF: 0.96
    iZone: 0
    kTrackScrubFactor: 1.0
    pathKs: 2
    verbose: 0 # 0 or 1
    compressorEnabled: 0 # 0 or 1
    useAutoAim: 1
    maxVel: 120 # inches/s
    maxAccel: 60 # inches/s^2
    trackWidth: 23 # inches
    wheelbaseLength: 21.5 #inches
    wheelDiameter: 6.122 #inches
    logTeleOp: 1
    logAuto: 1
    teleopFieldCentric: 0
    badLogEnabled: 1
