subsystems:
    drivetrain:
        implemented: true
        talons:
            leftMain: 15
            leftFollower: -1
            rightMain: 13
            rightFollower: -1
            flAzimuth: -1
            blAzimuth: -1
            frAzimuth: -1
            brAzimuth: -1
        swerveModulesConfig:
            modules:
                frontLeft:
                    drive: leftMain
                    azimuth: flAzimuth
                    encoderOffset: 2837
                frontRight:
                    drive: rightMain
                    azimuth: frAzimuth
                    encoderOffset: 3335
                backLeft:
                    drive: leftFollower
                    azimuth: blAzimuth
                    encoderOffset: 5
                backRight:
                    drive: rightFollower
                    azimuth: brAzimuth
                    encoderOffset: 2582
            drivePid:
                - slot0:
                    kP: 3.0 # 0.18 # TODO: tune PID, these are temporary PID values from Zeta
                    kI: 0.03 # 0.018
                    kD: 36 # 3.6
                    kF: 0.96
            azimuthPid:
                - slot0:
                    kP: 1.0
                    kI: 0.001
                    kD: 10
                    kF: 0
        pidConfig:
            - slot0:
                  kP: 3.0 # 0.18 # TODO: tune PID, these are temporary PID values from Zeta
                  kI: 0.03 # 0.018
                  kD: 36 # 3.6
                  kF: 0.96
        invertMotor:
            - rightMain
        constants:
            pigeonId: 9
            pigeonOnTalon: -1
            currentFloorCheck: .12
            currentEpsilonCheck: .2
            rpmFloorCheck: 2000
            rpmEpsilonCheck: 60
            openLoopRampRate: 0.8
            isSwerve: 0
            encPPR: 999
            azimuthEncPPR: 4096
            azimuthAllowableErrorTicks: 10
    shooter:
        implemented: false
    turret:
        implemented: false
    hopper:
        implemented: false
pcm: 8
constants:
    maxTicks: 14000 # ticks per 100ms TODO test actual maxTicks value
    sensorPhase: 0
    kLooperDt: .010
    kP: 3.0 # 0.18 # TODO: tune PID, these are temporary PID values from Zeta
    kI: 0.03 # 0.018
    kD: 36 # 3.6
    kF: 0.96
    iZone: 0
    kTrackScrubFactor: 1.0
    pathKs: 2
    verbose: 0 # 0 or 1
    compressorEnabled: 0 # 0 or 1
    useAutoAim: 1
    maxVel: 120 # inches/s
    maxAccel: 60 # inches/s^2
    trackWidth: 23 # inches
    wheelbaseLength: 21.5 #inches
    wheelDiameter: 6.122 #inches
    logTeleOp: 1
    logAuto: 1
    teleopFieldCentric: 0
    badLogEnabled: 1
