$extends: base
subsystems:
    drivetrain:
        implemented: true
        talons:
            leftMain: 15
            leftFollower: 14
            leftFollowerTwo: -1
            rightMain: 13
            rightFollower: 12
            rightFollowerTwo: -1
        invertMotor:
            - rightMain
        constants:
            pigeonId: 9
            kP: 3.0 # 0.18 # TODO: tune PID, these are temporary PID values from Zeta
            kI: 0.03 # 0.018
            kD: 36 # 3.6
            kF: 0.96
            encPPR: 999
pcm: 8
constants:
    maxVel: 120 # inches/s
    maxAccel: 60 # inches/s^2
    trackWidth: 23 # inches
    wheelDiameter: 6.122 #inches
    logTeleop: 1
    logAuto: 1
    badLogEnabled: 1
