$abstract: true
subsystems:
    drivetrain:
        implemented: false
        constants:
            pigeonId: -1
            pigeonOnTalon: -1
            kP: 0.1 # 0.18 # TODO: tune PID, these are temporary PID values from Zeta
            kI: 0.0001 # 0.018
            kD: 4.0 # 3.6
            kF: 0.0475813
            iZone: 0
            currentFloorCheck: .12
            currentEpsilonCheck: .2
            rpmFloorCheck: 2000
            rpmEpsilonCheck: 60
            openLoopRampRate: 0.8
    climber:
        implemented: false
    collector:
        implemented: false
        invertMotor:
            - intake
        constants:
            kP: 0
            kI: 0
            kD: 0
            kF: 0.0545
    hopper:
        implemented: false
        invertMotor:
            - spindexer
    shooter:
        implemented: false
        constants:
            kP: 0.15 #0.30
            kI: 0
            kD: 2.5 #4.5
            kF: 0.053 #0.00953253
            currentFloorCheck: .12
            currentEpsilonCheck: .2
            rpmFloorCheck: 2000
            rpmEpsilonCheck: 60
            velocityThreshold: 500
    turret:
        implemented: false
        constants: # TODO: tune [P, I, D]
            kP: 2.83 # 1.981 # 1.645
            kI: 0
            kD: 0
            kF: 0 # Should be 0 for position control
            encPPR: 4124.6
    ledmanager:
        implemented: false
    camera:
        implemented: false
pcm: -1
constants:
    maxVel: 120 #inch/s
    maxAccel: 60 #inch/s^2
    sensorPhase: 0
    kLooperDt: .015
    kTrackScrubFactor: 1.0
    pathKs: 2
    verbose: 0 # 0 or 1
    compressorEnabled: 0 # 0 or 1
    badLogEnabled: 0
    logTeleOp: 0
    logAuto: 0
    useAutoAim: 1

