subsystems:
    drivetrain:
        implemented: true
        talons:
            leftMain: 2
            leftFollower: -1
            rightFollower: -1
            rightMain: 1
            flAzimuth: -1
            frAzimuth: 3
            blAzimuth: -1
            brAzimuth: -1
        swerveModules:
            frontLeft:
                drive: leftMain
                azimuth: flAzimuth
                encoderOffset: 4035
            frontRight:
                drive: rightMain
                azimuth: frAzimuth
                encoderOffset: 3335
            backLeft:
                drive: leftFollower
                azimuth: blAzimuth
                encoderOffset: 5
            backRight:
                drive: rightFollower
                azimuth: brAzimuth
                encoderOffset: 2582
        drivePid:
            kP: 1.6
            kI: 0.001
            kD: 15.0
            kF: 0.5383998
        azimuthPid:
            kP: 2.0
            kI: 0
            kD: 10.0
            kF: 0
        constants:
            pigeonId: 13
            pigeonOnTalon: -1
            kP: 0.1 # 0.18 # TODO: tune PID, these are temporary PID values from Zeta
            kI: 0.0001 # 0.018
            kD: 4.0 # 3.6
            kF: 0.0475813
            iZone: 0
            currentFloorCheck: .12
            currentEpsilonCheck: .2
            rpmFloorCheck: 2000
            rpmEpsilonCheck: 60
            openLoopRampRate: 0.8
            encPPR: 4096 # CTRE mag encoder
            azimuthEncPPR: 4096
            azimuthAllowableErrorTicks: 5
    turret:
        implemented: false
        talons:
            turret: 3
        pid:
            -   kP: 4 # 1.981 # 1.645
                kI: 0
                kD: 40
                kF: 0 # Should be 0 for position control
        constants:
            encPPR: 4096 # CTRE MagEncoder
    ledmanager:
        implemented: true
        canifier: 12
        constants:
            maxLevel: 25
pcm: -1
constants:
    maxTicks: 14000 # ticks per 100ms TODO test actual maxTicks value
    sensorPhase: 0
    kLooperDt: .010
    kTrackScrubFactor: 1.0
    logTeleOp: 0
    useAutoAim: 1
    wheelDiameter: 4.058 # inches
    trackWidth: 15.75 # inches
    maxVel: 30 # inches/s
    maxAccel: 50 # inches/s^2
    compressorEnabled: 1
    pathKs: .0125
    verbose: 0
    logTeleop: 1
    logAuto: 1
    badLogEnabled: 1
