$extends: zodiac_base
subsystems:
    climber:
        implemented: false
    hopper:
        implemented: false
    shooter:
        implemented: false
    turret:
        implemented: true
        talons:
            turret: 3
    ledmanager:
        implemented: false
        canifier: 7
    camera:
        implemented: false
        canifier: 19
constants:
    logTeleop: 1
    logAuto: 1
    badLogEnabled: 1
