$extends: base
subsystems:
    drivetrain:
        implemented: true
        talons:
            leftMain: 2
            leftFollowerOne: -1
            leftFollowerTwo: -1
            rightMain: 1
            rightFollowerOne: -1
            rightFollowerTwo: -1
        invertMotor:
            - leftMain
        constants:
            pigeonId: 13
            kP: 1.6
            kI: .001
            kD: 15
            kF: 0.5383998
            iZone: 30
            encPPR: 4096 # CTRE mag encoder
            currentFloorCheck: .3
            rpmFloorCheck: 750
    turret:
        implemented: true
        talons:
            turret: 3
        constants:
            encPPR: 4096 # CTRE MagEncoder
    ledmanager:
        implemented: true
        canifier: 12
pcm: -1
constants:
    wheelDiameter: 4.058 # inches
    trackWidth: 15.75 # inches
    maxVel: 30 # inches/s
    maxAccel: 50 # inches/s^2
    compressorEnabled: 1
    pathKs: .0125
    verbose: 0
    logTeleop: 1
    logAuto: 1
    badLogEnabled: 1
