$extends: base
subsystems:
    drivetrain:
        implemented: true
        talons:
            leftMain: 2
            leftFollower: -1
            rightFollower: -1
            rightMain: 1
            flAzimuth: -1
            frAzimuth: 3
            blAzimuth: -1
            brAzimuth: -1
        swerveModules:
            frontLeft:
                drive: leftMain
                azimuth: flAzimuth
                encoderOffset: 4035
            frontRight:
                drive: rightMain
                azimuth: frAzimuth
                encoderOffset: 3335
            backLeft:
                drive: leftFollower
                azimuth: blAzimuth
                encoderOffset: 5
            backRight:
                drive: rightFollower
                azimuth: brAzimuth
                encoderOffset: 2582
        drivePid:
            kP: 1.6
            kI: 0.001
            kD: 15.0
            kF: 0.5383998
        azimuthPid:
            kP: 2.0
            kI: 0
            kD: 10.0
            kF: 0
        constants:
            encPPR: 4096 # CTRE mag encoder
            azimuthEncPPR: 4096
            pigeonId: 13
            azimuthAllowableErrorTicks: 5
    turret:
        implemented: false
        talons:
            turret: 3
        constants:
            encPPR: 4096 # CTRE MagEncoder
    ledmanager:
        implemented: true
        canifier: 12
        constants:
            maxLevel: 25
pcm: -1
constants:
    wheelDiameter: 4.058 # inches
    trackWidth: 15.75 # inches
    maxVel: 30 # inches/s
    maxAccel: 50 # inches/s^2
    compressorEnabled: 1
    pathKs: .0125
    verbose: 0
    logTeleop: 1
    logAuto: 1
    badLogEnabled: 1
