$extends: zodiac_base
subsystems:
    drivetrain:
        invertMotor:
            - rightMain
    turret:
        constants:
            minPos: -4220
            maxPos: -1072
constants:
    wheelDiameter: 6.15 #inches
