$abstract: true
subsystems:
    drivetrain:
        implemented: true
        falcons:
            leftMain: 17
            leftFollower: 1
            leftFollowerTwo: -1
            rightMain: 14
            rightFollower: 15
            rightFollowerTwo: -1
        invertMotor:
            - leftMain
        constants:
            pigeonId: 9
            pigeonOnTalon: -1
            kP: 0.1 # 0.18 # TODO: tune PID, these are temporary PID values from Zeta
            kI: 0.0001 # 0.018
            kD: 4.0 # 3.6
            kF: 0.0475813
            iZone: 0
            encPPR: 22220.8
            currentFloorCheck: .12
            currentEpsilonCheck: .2
            rpmFloorCheck: 2000
            rpmEpsilonCheck: 60
            openLoopRampRate: 0.8
    climber:
        implemented: true
        talons:
            elevator: 6
        solenoids:
            deployer: 5
    collector:
        implemented: true
        talons:
            intake: 11
        solenoids:
            arm: 0
        constants:
            kP: 0.2
            kI: 0
            kD: 0
            kF: 0
    hopper:
        implemented: true
        talons:
            spindexer: 4
            elevator: 5
        invertMotor:
            - spindexer
        solenoids:
            feederFlap: 4
    shooter:
        implemented: true
        falcons:
            shooterMain: 3
            shooterFollower: 2
        constants:
            kP: 0.15 #0.30
            kI: 0
            kD: 2.5 #4.5
            kF: 0.053 #0.00953253
            currentFloorCheck: .12
            currentEpsilonCheck: .2
            rpmFloorCheck: 2000
            rpmEpsilonCheck: 60
            velocityThreshold: 500
    turret:
        implemented: true
        talons:
            turret: 13
        constants: # TODO: tune [P, I, D]
            kP: 2.83 # 1.981 # 1.645
            kI: 0
            kD: 0
            kF: 0 # Should be 0 for position control
            encPPR: 4124.6
    ledmanager:
        implemented: false
pcm: 8
constants:
    trackWidth: 25 #inches
    maxVel: 120 #inch/s
    maxAccel: 60 #inch/s^2
    sensorPhase: 0
    kLooperDt: .030
    kTrackScrubFactor: 1.0
    pathKs: 2
    verbose: 0 # 0 or 1
    compressorEnabled: 1 # 0 or 1
    badLogEnabled: 0
    logTeleOp: 0
    logAuto: 0
    useAutoAim: 1
