$extends: base
subsystems:
    drivetrain:
        implemented: true
        falcons:
            flDrive: -2
            blDrive: -1
            frDrive: -13
            brDrive: -14
        talons:
            flAzimuth: 4
            frAzimuth: 11
            blAzimuth: 3
            brAzimuth: 12
        swerveModules:
            frontLeft:
                drive: flDrive
                azimuth: flAzimuth
                encoderOffset: 1433
                invertSensorPhase: false
            frontRight:
                drive: frDrive
                azimuth: frAzimuth
                encoderOffset: -3362
                invertSensorPhase: true
            backLeft:
                drive: blDrive
                azimuth: blAzimuth
                encoderOffset: -3425
                invertSensorPhase: true
            backRight:
                drive: brDrive
                azimuth: brAzimuth
                encoderOffset: -2561
                invertSensorPhase: true
        drivePid:
            kP: 0.1
            kI: 0.0001
            kD: 4.0
            kF: 0.0475813
        azimuthPid:
            kP: 0.7
            kI: 0
            kD: 20
            kF: 0
        constants:
            encPPR: 22220.8
            azimuthEncPPR: 4096
            azimuthAllowableErrorTicks: 10
            pigeonId: 32
pcm: 8
constants:
    trackWidth: 25 #inches
    wheelDiameter: 6.32 #inches
    logTeleOp: 1
    logAuto: 1
    badLogEnabled: 1
    compressorEnabled: 0
