$extends: base
subsystems:
    drivetrain:
        falcons:
            leftMain: 2
            leftFollower: 1
            rightMain: 13
            rightFollower: 14
        talons:
            flAzimuth: 4
            frAzimuth: 11
            blAzimuth: 3
            brAzimuth: 12
        swerveModules:
            frontLeft:
                drive: leftMain
                azimuth: flAzimuth
                encoderOffset: 1409
            frontRight:
                drive: rightMain
                azimuth: frAzimuth
                encoderOffset: 3335
            backLeft:
                drive: leftFollower
                azimuth: blAzimuth
                encoderOffset: 5
            backRight:
                drive: rightFollower
                azimuth: brAzimuth
                encoderOffset: 2582
        drivePid:
            kP: 0.1
            kI: 0.0001
            kD: 4.0
            kF: 0.0475813
        azimuthPid:
            kP: 3.0
            kI: 0.05
            kD: 20
            kF: 0
        constants:
            encPPR: 22220.8
            azimuthEncPPR: 4096
            pigeonId: 32
pcm: 8
constants:
    trackWidth: 25 #inches
    wheelDiameter: 6.32 #inches
    logTeleop: 1
    logAuto: 1
    badLogEnabled: 1
    compressorEnabled: 0
