$extends: base
subsystems:
    drivetrain:
        implemented: true
        falcons:
            flDrive: 2
            blDrive: 1
            frDrive: 13
            brDrive: 14
        talons:
            flAzimuth: 4
            frAzimuth: 11
            blAzimuth: 3
            brAzimuth: 12
        invertMotor:
            - frAzimuth
            - blAzimuth
            - brAzimuth
            - frDrive
            - brDrive
        swerveModules:
            frontLeft:
                drive: flDrive
                azimuth: flAzimuth
                encoderOffset: 1443
                invertSensorPhase: false
            frontRight:
                drive: frDrive
                azimuth: frAzimuth
                encoderOffset: 3356
                invertSensorPhase: true
            backLeft:
                drive: blDrive
                azimuth: blAzimuth
                encoderOffset: 3450
                invertSensorPhase: true
            backRight:
                drive: brDrive
                azimuth: brAzimuth
                encoderOffset: 2551
                invertSensorPhase: true
        drivePid:
            kP: 0.1
            kI: 0.0001
            kD: 4.0
            kF: 0.0499
        azimuthPid:
            kP: 2.0
            kI: 0
            kD: 30
            kF: 0
        constants:
            encPPR: 12275.7
            azimuthEncPPR: 4096
            azimuthAllowableErrorTicks: 10
            pigeonId: 32
            azimuthHomeAdjustmentDegrees: 0 # 0.4
    ledmanager:
        implemented: true
        canifier: 18
        constants:
            raveEnabled: 0
            raveSpeed: 0.05
    turret:
        implemented: true
        talons:
            turret: 9
    shooter:
        implemented: true
        falcons:
            shooterMain: 0
            shooterFollower: 15
    hopper:
        implemented: true
        talons:
            spindexer: 10
            elevator: 5
        solenoids:
            feederFlap: 4
pcm: 8
constants:
    trackWidth: 21 #inches
    wheelbaseLength: 21.5 #inche
    wheelDiameter: 3.8989736842 #inches
    maxVel: 240  # 22560 native units
    maxAccel: 120
    logTeleOp: 1
    logAuto: 1
    badLogEnabled: 1
    compressorEnabled: 0
    kLooperDt: .030 # seconds
