$extends: zodiac_base
subsystems:
    drivetrain:
        falcons:
            leftMain: 2
            leftFollower: 1
            rightMain: 13
            rightFollower: 14
        talons:
            flAzimuth: 4
            frAzimuth: 11
            blAzimuth: 3
            brAzimuth: 12
        swerveModules:
            frontLeft:
                drive: leftMain
                azimuth: flAzimuth
                encoderOffset: 1409
            frontRight:
                drive: rightMain
                azimuth: frAzimuth
                encoderOffset: 3335
            backLeft:
                drive: leftFollower
                azimuth: blAzimuth
                encoderOffset: 5
            backRight:
                drive: rightFollower
                azimuth: brAzimuth
                encoderOffset: 2582
    hopper:
        invertMotor:
            - elevator
    shooter:
        falcons:
            shooterMain: 3
            shooterFollower: 2
    turret:
        constants:
            minPos: -3802
            maxPos: -757
    ledmanager:
        implemented: true
        canifier: 18
    camera:
        implemented: true
        canifier: 19
constants:
    wheelDiameter: 6.32 #inches
    logTeleop: 1
    logAuto: 1
    badLogEnabled: 1
