$abstract: true
$extends: base
subsystems:
    drivetrain:
        implemented: true
        falcons:
            leftMain: 17
            leftFollower: 1
            leftFollowerTwo: -1
            rightMain: 14
            rightFollower: 15
            rightFollowerTwo: -1
        invertMotor:
            - leftMain
        constants:
            pigeonId: 9
            encPPR: 22220.8
    climber:
        talons:
            elevator: 12
        solenoids:
            deployer: 5
    collector:
        implemented: true
        falcons:
            intake: 11
        solenoids:
            arm: 0
    hopper:
        implemented: true
        talons:
            spindexer: 4
            elevator: 5
        solenoids:
            feederFlap: 4
    shooter:
        implemented: true
        falcons:
            shooterMain: -1
            shooterFollower: -1
    turret:
        implemented: true
        talons:
            turret: 13
            offset: 370
pcm: 8
constants:
    maxVel: 105 #inch/s
    trackWidth: 25 #inches
    compressorEnabled: 1 # 0 or 1
